# This file provides instructions for packaging.

`Tie-Moose`
	perl_version_from m`Tie::Moose`;
	version_from      m`Tie::Moose`;
	readme_from       m`Tie::Moose`;
	test_requires     p`Test::More 0.61` ;
	.

